### ISSUE TITLE
Don't build the service provider to detect if a service is registered

### ISSUE THREAD

**Issue by davidfowl** [jchannon/Botwin#13]
https://github.com/jchannon/Botwin/blob/92bb7732be433cb70c22fe76e694a793d246db5b/src/BotwinExtensions.cs#L130

Instead, you should use TryAdd*. In this case `TryAddSingleton<IAssemblyProvider, AssemblyProvider>()`. See https://github.com/aspnet/Mvc/blob/900a5c7c4c789e71bf18e8e90bf9b28b4e51013f/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L145

**Comment by jchannon** [comment]
Cheers will amend that.

On another note, is it ok to build it to get the provider to "get" a
registered item?
