### ISSUE TITLE
Use the ILogger stuff to add debug level tracing

### ISSUE THREAD

**Issue by JoeStead** [jchannon/Botwin#21]
As we're using the `IServiceProvider` provided by AspNetCore, we should hook up some of the other features, including enabling logging.

It's a pain to try and diagnose issues with things without any logging, we should implement trace/debug calls around the code base that can be configured with the ILoggerFactory

**Comment by jchannon** [comment]
I had a play with this by putting ILogger in BotwinModule but that means that everyone would need to have it in their constructors which is not what we want.  As the routes are just Func in ASPNetCore we don't really have anywhere where we can log what's going on inside them. We can log when routes are about to be hit etc but this pretty much gets logged with default logging anyway.  The user can do this OOTB:

```
  public HomeModule(ILogger<HomeModule> logger)
        {
            this.Get("/", async (req, res, routeData) =>
            {
                logger.LogInformation("OMG");
```

What we can probably do is log the execution of module before/after hooks easily as well as the global ones.

**Comment by JoeStead** [comment]
Yeah, I thought about this and didn't want to force a dependency on ILogger either. Could be useful for resolving modules/validators at startup too. The number of times people ask "Why isn't my module being picked up in Nancy" kind of justifies this logging imo
