### ISSUE TITLE
Botwin template includes unneeded Mac OSX file

### ISSUE THREAD

**Issue by shanselman** [jchannon/Botwin#31]
![image](https://user-images.githubusercontent.com/2892/31480269-b1a0f508-aed1-11e7-9af1-268a9d0a196c.png)

When you zipped this up and submitted it to NuGet, you left/leave in this Mac resource. It then shows up on Windows machines.

**Comment by jchannon** [comment]
Thanks. Will get that sorted within the next few hours and push a new
version. Will update the issue when done.

**Comment by JoeStead** [comment]
Probably worth pushing the changes we've made over the past week or so to Nuget too?

**Comment by jchannon** [comment]
Yup was thinking the same. Would like to get some perf eyes on the local
function pr if possible

**Comment by jchannon** [comment]
I've published a new template and looked at the inside of the nupkg and couldn't see anything untoward. Maybe uninstall/update the template and please verify if it's ok. Thanks

**Comment by shanselman** [comment]
fixed!

**Comment by jchannon** [comment]
Thanks for checking!
