### ISSUE TITLE
Need a BodyAsString extension method

### ISSUE THREAD

**Issue by jchannon** [jchannon/Botwin#34]
It would be nice to have a `BodyAsString()` method off of HttpRequest.

**Comment by BugAgain** [comment]
And how about a `BodyAsJsonObject()` method? Does that make sense to you?

**Comment by jchannon** [comment]
You can use Bind<T> for that already 😄

**Comment by BugAgain** [comment]
Great ;)
I'll take a deeper look at this report later if I can make some contributions.
Is the `BodyAsString()` an extension method?

**Comment by jchannon** [comment]
Yup it would come off HttpRequest and probably end up in this folder https://github.com/jchannon/Botwin/tree/master/src/Request as a StreamExtensions.cs

**Comment by grandchamp** [comment]
You mean this?

```
var response = await this.httpClient.GetAsync("/");
var body = response.BodyAsString();
```

**Comment by jchannon** [comment]
context.Request.Body.AsString

**Comment by BugAgain** [comment]
I don't know if the changes will meet your requeriments. But feel free to take the PR #36 or not ;)

Thanks!

**Comment by leomicheloni** [comment]
Hi,
 Is this still open? I would like to give it a try, thanks!

**Comment by jchannon** [comment]
@leomicheloni  - @BugAgain has sent a PR so I think they have it covered.  Feel free to spot anything that needs changing/adding and raise an issue and if relevant you can setup a PR. Keep an eye out on the labels on the issues too. Thanks
