### ISSUE TITLE
Test dotnet new botwin

### ISSUE THREAD

**Issue by jchannon** [jchannon/Botwin#40]
Run 
```
dotnet new -i BotwinTemplate

dotnet new botwin -n MyBotwinApp
```

Currently seeing object reference error but others have reported all is ok.

**Comment by JoeStead** [comment]
I also get nullreference exception

**Comment by jchannon** [comment]
Can you run `dotnet new --debug:reinit` then install the template and try running it

**Comment by jchannon** [comment]
New version released.
