### ISSUE TITLE
Add support for camelCasing in DefaultJsonResponseNegotiator

### ISSUE THREAD

**Issue by pdwetz** [jchannon/Botwin#53]
The default Json.Net casing strategy is PascalCasing, which is counter to what a lot of json-based API consumers expect. It'd be nice to easily switch to camelCasing instead.

https://www.newtonsoft.com/json/help/html/NamingStrategyCamelCase.htm

I have a local implementation within my project, but I could pull it out into a Botwin pull request if desired. It's pretty simple and just accepts IContractResolver in the contructor of the negotiator, which I then use in the SerializeObject call.

**Comment by jchannon** [comment]
Good point. I think until we open Botwin up to extensions eg/use your own
serializer etc we should hard code this in the response negotiator.

Would you like to send a PR for that?

**Comment by pdwetz** [comment]
Will do.
