### ISSUE TITLE
Question about services lifecycles

### ISSUE THREAD

**Issue by jonathanschein** [jchannon/Botwin#61]
I´m trying to use the Botwin library with EF Core. I registered the DbContext using services.AddDbContext (By default sets ServiceLifetime.Scoped) but I noticed that my application uses the same DbContext in each request. Then I noticed that the modules are created once, regardless of whether they are registered at IoC container as transient. So each dependency injected don't respect its configured Lifetime. Is this a desing decision?

Thanks in advance.

**Comment by jchannon** [comment]
Hi

That is odd. Each module when calling services.AddBotwin are registered as
transient see here -
https://github.com/jchannon/Botwin/blob/master/src/BotwinExtensions.cs#L167

Simplest test is to create a Guid property in the module and assign a new
guid to it in the constructor. Return that guid property in a route and
test its value. In theory it should be unique per request.

I'm happy to test that or feel free to do it.

**Comment by jchannon** [comment]
Just tested and you've found a beauty of an issue here!  Will try and resolve it ASAP

**Comment by jchannon** [comment]
@jonathanschein Botwin v3 is now out, can you check all is ok 👍

**Comment by jchannon** [comment]
brill
