### ISSUE TITLE
Route Maps

### ISSUE THREAD

**Issue by dcomartin** [jchannon/Botwin#73]
When Botwin loads it has to construct all of the BotwinModules, which in turn has to construct all of its dependencies. I assume it does this so it can determine all the relevant routes so it knows which Module to construct when an associated request comes in.

This can be problematic if you have (like I often do) a lot of BotwinModules.  Each module generally only defines one or two routes.  This can slow down startup because of DI basically.

I've been thinking if it would make sense to have some sort of interface that Botwin could look for at startup/load to get routes and mappings instead of constructing all Modules.

https://gist.github.com/dcomartin/81f09f24aeea004b831d96b0d49c3d90

Thoughts?

**Comment by jchannon** [comment]
I understand your point, Nancy does the same thing and then caches the modules and are invoked per request, maybe we should look to do the same.  Out of interest how slow is your startup, in the real world is it an issue for example?

**Comment by dcomartin** [comment]
For Botwin, this isn't an issue yet as i don't have enough of them (yet).  But it is an issue with me in real world with Nancy.  That's why I was bringing this up here because Botwin is more in line going forward for me.

**Comment by JoeStead** [comment]
I have an idea that will solve this without manually maintaining a map. I'm going to be experimenting with it and see where I get to :)

**Comment by JoeStead** [comment]
This got... messy, quickly. Although I had the basic idea working, I wouldn't feel comfortable introducing it to the project, because of complexity. 

I guess guidance is: Keep your modules simple and your dependency chains sane, and startup time should be fine
