### ISSUE TITLE
Sample release version doesn't work

### ISSUE THREAD

**Issue by raminmjj** [jchannon/Botwin#82]
there is no problem with Debug mode.
but in release and publish mode, routing doesn't seems work.
![2018-01-24](https://user-images.githubusercontent.com/991847/35329394-f73303fa-0114-11e8-86b2-4771b97137b8.png)

**Comment by jchannon** [comment]
If routing isn't working why is it logging `We hit a route!` ?

**Comment by jchannon** [comment]
Oh it's returning 404. Hmm

**Comment by JoeStead** [comment]
Can reproduce on MacOS too with:

`dotnet publish -c Release`

It's fine when published with Debug though. This should be a fun one

**Comment by jchannon** [comment]
I'm guessing assembly scanning

**Comment by JoeStead** [comment]
Yeah, but the AfterHook is writing out "We hit a route" to stdout. If it was assembly scanning I'd expect that to fail too.

**Comment by JoeStead** [comment]
Ahh nevermind, that afterhook is misleading. It's hit even when no route is resolved :)

**Comment by jchannon** [comment]
Thought that might be the case. Hmm

**Comment by JoeStead** [comment]
As a workaround, when adding the Botwin services, you can tell it what assemblies to scan:
` services.AddBotwin(Assembly.GetAssembly(typeof(Startup)));`

It's sort of nasty, but will allow you to publish to release mode correctly until we can come up with a way of doing it properly

**Comment by jchannon** [comment]
I changed it because of unit tests *I think*
https://github.com/jchannon/Botwin/pull/72/files#diff-82112b99eae34877f111696bbe53aa64R153

Going to have to find out the best of way of doing this I think

**Comment by JoeStead** [comment]
I tried I a few variants of `Assembly.Get` and all of them failed with similar problems

**Comment by jchannon** [comment]
@davidfowl @poke any ideas

**Comment by jchannon** [comment]
@raminmjj @richardprice can you pull the branch in the linked PR and run the sample or your own application to see if it works now. thanks
