### ISSUE TITLE
Preflight OPTIONS requests

### ISSUE THREAD

**Issue by bazwilliams** [jchannon/Botwin#91]
When using CORS some of our integrations send a preflight request with an `OPTIONS` method. Nancy seems to provide this out of the box. I'm not getting the same behaviour when I send an `OPTIONS` request to my Botwin reimplementation. 

Preflight request information:
https://docs.microsoft.com/en-us/aspnet/core/security/cors#preflight-requests

**Comment by bazwilliams** [comment]
Just realised I was testing without sending an `origin` header:

The `AddCors` / `UseCors` does exactly what I'd hoped it would.

**Comment by jchannon** [comment]
Brill!
